### PR TITLE
New test: which Content-Types are considered valid for script execution?

### PR DESCRIPTION
**Pull request by bdmussler**
NB: I was unsure how "testNumbers" are assigned so I picked 99 a placeholder.

The test determines whether browsers consider "application/json" and/or "text/json" as valid Content-Types for scripts.

==============================

Firefox 50:

https://blog.mozilla.org/security/2016/08/26/mitigating-mime-confusion-attacks-in-firefox/

[...]

Valid Content-Types for Scripts:
– “application/javascript”
– “application/x-javascript”
– “application/ecmascript”
– “application/json”<---
– “text/ecmascript”
– “text/javascript”
– “text/json”   <---

==============================

Firefox 60:

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/60

Security

The X-Content-Type-Options header, when set to no-sniff, now follows
the specification for JavaScript MIME types. In particular,
text/json and application/json are no longer valid values (bug 1431095).

==============================

### CODE REVIEW

**Comment by cachtinh** [comment]
Hi @bdmussler, 
Thank you very much for your interesting testcase! We are doing the code review and there are a few modifications we would like to make in your pull request, eg.:

- the configuration in `test_app/src/mime.types` could potentially affect other (future) testcases
- the use of 'let' in Javascript could be unsupported in some old browsers

It will be much faster for us to do so if we have push permission in your forked repository. Could you please give the permission for @khanhhongpham?

Thank you,
Tuyen

**Comment by tuyenee** [comment]
Hi @bdmussler ,
Thank you very much for your interesting testcase! We are doing the code review and there are a few modifications we would like to make in your pull request, eg.:

- the configuration in test_app/src/mime.types could potentially affect other (future) testcases

- the use of 'let' in Javascript could be unsupported in some old browsers

It will be much faster for us to do so if we have push permission in your forked repository. Could you please give the permission to @khanhhongpham ?

Thank you,
Tuyen

**Review by tuyenee — APPROVED** [review]

**Comment by tuyenee** [comment]
Happy new year, @bdmussler!

We are glad to have run and published the result of your testcase: [https://canitrust.in/detail/99](https://canitrust.in/detail/99)!

Thank you very much for your contribution and we are looking forward to hearing from you more in the future!
Tuyen

PS: the test will be run again against newly added browser versions.

**Comment by bdmussler** [comment]
Great, thank you @tuyenee!

**Pull request merged**
